# https://github.com/JohnnyMorganz/StyLua
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferSingle"
column_width = 200
collapse_simple_statement = "FunctionOnly"

[sort_requires]
enabled = false
